version: "3.8"

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
      - db
    networks:
      - dev

  backend:
    build: 
      context: ./smth_backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=smth_database
      - DB_USER=andrejadajkin
      - DB_PASSWORD=12345678
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build: 
      context: ./my-frontend
    ports:
    - "3000:3000"
    networks:
      - dev

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smth_database
      MYSQL_USER: andrejadajkin
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev

volumes:
  db_data:
    driver: local