services:
  backend:
    build: 
      context: ./smth_backend
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/smth_database
      SPRING_DATASOURCE_USERNAME: andrejadajkin
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build: 
      context: ./my-frontend
    ports:
      - "8081:8081"
    networks:
      - dev

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: smth_database
      MYSQL_USER: andrejadajkin
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev

volumes:
  db_data:
    driver: local

networks:
  dev:
    driver: bridge