networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend 
      - db
    networks:
      - dev

  backend:
    build: 
      context: ./smth_backend
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=smth_database
      - DB_USER=andrejadajkin
      - DB_PASSWORD=12345678
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build: 
      context: ./my-frontend
    networks:
      - dev

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smth_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev

volumes:
  db_data: